### ISSUE TITLE
Como usuario existente, quiero poder iniciar sesión en mi cuenta para acceder a mis funciones de gestión de inventario.

### ISSUE THREAD

**Issue by Annorakx** [4GeeksAcademy/ProjectoFinal_Inventario#3]
- [ ] Criterios de aceptación:
1.Puedo acceder a un formulario de inicio de sesión desde la página de inicio.
2.Puedo ingresar mi dirección de correo electrónico y contraseña.
3.Al iniciar sesión correctamente, se me dirige al panel de control de la aplicación donde puedo administrar mi inventario.

**Comment by gespana26** [comment]
- [x] se crea modelo de la BD, se crean las tablas.
- [x] Se crea los "endpoints" para Login y signup.
- [x] Se realiza pruebas desde thunder Client.
- [x]  Se crea las funciones de Login y signup en el Flux.
- [x] se realizan ajustes y validaciones.
- [x] Se realiza la integración contra los formularios de login y signup.
- [x] Se realizan pruebas satisfactorias.
